import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import twitterLogo from "../public/twitter-logo.svg";
import { Heading, Card, Text, Button } from "degen";
import Web3Modal from "web3modal";

// misc imports:
const TWITTER_HANDLE = "clague17";
const TWITTER_LINK = `https://twitter.com/${TWITTER_HANDLE}`;

// Wallet stuff
let web3Modal;
if (typeof window !== "undefined") {
  web3Modal = new Web3Modal({
    network: "mainnet", // optional
    cacheProvider: true,
  });
}

type Subscription = {
  title: string;
  author: string;
  coverImage: string;
};

const subscriptions: Array<Subscription> = [
  {
    title: "Luis",
    author: "LuisAuthor",
    coverImage: "lol.jpeg",
  },
  { title: "L2", author: "L2Author", coverImage: "lol2.jpeg" },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Liquid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="container" className="flex flex-col justify-center">
        <main className="flex w-full justify-center  border-b-2 border-black">
          <div
            id="navcontainer"
            className="align-center mx-5 flex w-full flex-row justify-between"
          >
            <img src="/liquid_banner.svg" alt="liquid" className="w-64" />
            <div id="right-navbar" className="flex">
              <div className="flex flex-row m-auto justify-between">
                <span className="p-4">
                  <Text variant="large">Creator</Text>
                </span>
                <span className="p-4">
                  <Text variant="large">Buyer</Text>
                </span>
                <div className="m-auto">
                  <Button>Connect Wallet</Button>
                </div>
              </div>
            </div>
          </div>
        </main>
        <div className="w-[40%] m-auto">
          <div id="main-content" className="relative w-full py-5">
            <Card padding="6" shadow>
              <Heading>Check out these other subscriptions</Heading>
              <Text>Sign in with your wallet to make your own!</Text>
              {subscriptions.map((sus, idx) => (
                <div className="m-6">
                  <Card hover padding="6">
                    <Heading>{sus.title}</Heading>
                    <Text>{sus.author}</Text>
                  </Card>
                </div>
              ))}
            </Card>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          className="flex items-center justify-center font-bold"
          href={TWITTER_LINK}
          target="_blank"
          rel="noreferrer"
        >
          <Image alt="Twitter Logo" width={35} height={35} src={twitterLogo} />
          {`built by @${TWITTER_HANDLE}`}
        </a>
      </footer>
    </div>
  );
};

export default Home;
